# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_comments', '0003_add_submit_date_index'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='comment',
            index_together=set([('content_type', 'object_pk')]),
        ),
    ]
