# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0003_add_submit_date_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='object_pk',
            field=models.CharField(max_length=255, verbose_name='object ID'),
        ),
    ]
